version: '2'
services:
  elasticsearch:
    image: mrlesmithjr/elasticsearch:latest
    volumes:
      - "./.data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  logstash:
    depends_on:
      - elasticsearch
    image: mrlesmithjr/logstash:alpine
    links:
      - elasticsearch
    ports:
      - "5044:5044"
      - "10514:10514"
      - "10514:10514/udp"
    restart: always
